[package]
name = "rhash"
version = "0.1.0"
edition = "2024"

[dependencies]
blake2 = "0.10.6"
blake3 = "1.8.2"
clap = { version = "4.5.40", features = ["derive"] }
md5 = "0.8.0"
sha2 = "0.10.9"
anyhow = "1.0.98"
